backend:
  name: github
  repo: GSA/10x
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  branch: redesign-theme
  preview_context: federalist/build

media_folder: public/images
public_folder: public/images

collections:
  - name: settings
    extension: json
    publish: false
    label: Site Settings
    label_singular: Site Settings
    create: false
    delete: false
    show_preview_links: false
    identifier_field: settings
    editor:
      preview: false
    files:
      - label: Settings
        name: settings
        file: cms/settings.json
        fields:
          - label: Settings
            name: settings
            widget: hidden
            default: settings
          - label: Site Title
            name: title
            widget: string
          - label: Site Description
            name: description
            widget: string
          - name: customFields
            label: Custom Fields
            widget: list
            fields:
              - name: key
                label: Key
                widget: string
              - name: value
                label: Value
                widget: string
  - name: menu
    extension: json
    label: Menus
    label_singular: Menu
    folder: cms/menus
    create: true
    delete: true
    editor:
      preview: false
    slug: "{{key}}"
    fields:
      - name: key
        label: key
        widget: string
      - name: items
        label: Items
        widget: list
        summary: "{{fields.text}}"
        fields:
          - label: Prefix
            name: prefix
            widget: string
            required: false
          - label: Text
            name: text
            widget: string
          - label: Link
            name: link
            widget: string
          - label: Description
            name: desc
            width: string
          - label: Items
            name: items
            widget: list
            fields:
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: string
  - name: new-pages
    label: Layout Pages
    extension: json
    label_singular: Layout Page
    folder: cms/content/new-page
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    identifier_field: slug
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Headline"
        name: "subtitle"
        widget: "string"
        required: false
      - widget: string
        name: "slug"
        label: "Slug"
        required: true
        pattern:
          [
            "^[a-z0-9]+(?:-[a-z0-9]+)*$",
            "A slug can have no spaces or special characters",
          ]
        hint: "The project URL (do not include folder or file extension)"

      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: Title
            name: title
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
              - label: "Headline"
                name: "subtitle"
                widget: text

          - label: "Markdown"
            name: "markdown"
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Fullwidth
                name: fullwidth
                widget: boolean
                required: false
              - label: "Body"
                name: "body"
                widget: "markdown"

          - label: Callout
            name: callout
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
                required: false
              - label: "Subtitle"
                name: "subtitle"
                widget: string
                required: false
              - label: "Text"
                name: "text"
                widget: text
                required: false
              - label: Button
                name: button
                widget: "object"
                required: false
                fields:
                  - label: Text
                    name: "text"
                    widget: string
                    required: false
                  - label: Link
                    name: "link"
                    widget: string
                    required: false
              - label: Items
                name: items
                widget: list
                summary: "{{ fields.title }}"
                fields:
                  - label: Title
                    name: "title"
                    widget: string
                    required: false
                  - label: Text
                    name: "text"
                    widget: string
                    required: false

          - label: Break
            name: break
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Color
                name: color
                widget: select
                required: false
                options:
                  [
                    "primary-lighter",
                    "secondary",
                    "accent-warm",
                    "accent-cool",
                    "base-lighter",
                  ]
              - label: variant
                name: variant
                widget: select
                required: false
                options: [0, "wide"]

          - label: Links
            name: links
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
                required: false
              - label: "Subtitle"
                name: "subtitle"
                widget: string
                required: false
              - label: "Text"
                name: "text"
                widget: string
                required: false
              - label: Button
                name: button
                widget: "object"
                required: false
                fields:
                  - label: Text
                    name: "text"
                    widget: string
                    required: false
                  - label: Link
                    name: "link"
                    widget: string
                    required: false
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Text
                    name: text
                    widget: string
                  - label: Link
                    name: link
                    widget: string

          - label: List
            name: list
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
                required: false
              - label: "Subtitle"
                name: "subtitle"
                widget: string
                required: false
              - label: "Text"
                name: "text"
                widget: string
                required: false
              - label: Button
                name: button
                widget: "object"
                required: false
                fields:
                  - label: Text
                    name: "text"
                    widget: string
                    required: false
                  - label: Link
                    name: "link"
                    widget: string
                    required: false
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                    required: false
                  - label: Text
                    name: text
                    widget: string
                    required: false

          - label: Cards
            name: cards
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
                required: false
              - label: "Text"
                name: "text"
                widget: string
                required: false
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Text
                    name: text
                    widget: string
                  - label: Link
                    name: "link"
                    widget: string

          - label: Projects
            name: projects
            widget: "object"
            fields:
              - label: Classname
                name: className
                widget: string
                required: false

      - label: Meta
        name: meta
        widget: "object"
        fields:
          - label: "Theme"
            name: "theme"
            required: false
            widget: "select"
            options: ["1", "2", "3", "4"]
  - name: page
    extension: json
    label: Pages
    label_singular: Page
    folder: cms/content/page
    create: true
    delete: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    identifier_field: title
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Theme"
        name: "theme"
        required: false
        widget: "select"
        options: ["1", "2", "3", "4"]
      - label: Meta
        name: Meta
        required: false
        widget: "object"
        fields:
          - label: Description
            name: description
            widget: string
            required: false
          - label: Facebook Image
            name: fbImg
            widget: image
            required: false
          - label: Twitter Image
            name: twImg
            widget: image
            required: false
      - label: "Hero Content"
        name: "hero"
        widget: "markdown"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: project
    extension: json
    label: Projects
    label_singular: Project
    folder: cms/content/project
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    identifier_field: slug
    fields:
      - widget: string
        name: "slug"
        label: "Slug"
        required: true
        pattern:
          [
            "^[a-z0-9]+(?:-[a-z0-9]+)*$",
            "A slug can have no spaces or special characters",
          ]
        hint: "The project URL (do not include folder or file extension)"
      - label: "Project Title"
        name: "title"
        widget: "string"
      - label: "Headline"
        name: "subtitle"
        widget: "string"
      - label: "Portfolio Card"
        name: "card"
        hint: "Customize the Card content that will display on the Portfolio page"
        widget: "object"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
            hint: "Cust card Title (defaults to Project Title)"
          - label: "Headline"
            name: "subtitle"
            required: false
            hint: "Custom card Headline (defaults to Project Headline)"
          - label: "Project Url"
            name: "projectUrl"
            widget: "string"
            required: false
            hint: "Valid full URL for the Portfilio card (defaults to Project Slug)"
          - label: "Excerpt"
            name: "excerpt"
            widget: "text"
            required: false
      - label: "Introduction"
        name: "intro"
        widget: "text"
      - label: "Content"
        name: "content"
        widget: "list"
        summary: "{{fields.title}}"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
          - label: "Phase Data"
            name: "phase"
            widget: "boolean"
            required: false
      - label: "Meta Data"
        name: "meta"
        widget: "object"
        fields:
          - label: "Type"
            name: "projectType"
            widget: "select"
            options: ["Innovation", "Transformation", "Enhancement"]
          - label: "Template"
            name: "template"
            widget: "select"
            options:
              - label: "1"
                value: "1"
              - label: "2"
                value: "2"
              - label: "3"
                value: "3"
              - label: "4"
                value: "4"
              - label: "5"
                value: "5"
              - label: "6"
                value: "6"
          - label: "Phase"
            name: "phaseData"
            widget: "object"
            collapsed: true
            fields:
              - label: "Phase"
                name: "phase"
                widget: "select"
                options: ["1", "2", "3", "4"]
              - label: "Status"
                name: "status"
                widget: "select"
                options:
                  [
                    { label: "In Progress", value: "1" },
                    { label: "Done", value: "2" },
                    { label: "Graduated", value: "3" },
                  ]
                default: "InProgress"
              - label: "Message"
                name: "message"
                hint: "Override the default Phase status message."
                widget: "string"
                required: false
          - label: "Topics"
            name: "topics"
            widget: "string"
            hint: "Separate tag values by comma."
            required: false
          - label: "Summary"
            name: "summary"
            widget: "list"
            required: false
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
          - label: "Team"
            name: "team"
            widget: "object"
            required: false
            fields:
              - label: "Idea Submitter"
                name: "submitter"
                widget: "string"
                required: false
              - label: "Members"
                name: "members"
                widget: "text"
                required: false
          - label: "Links"
            name: "links"
            widget: "list"
            required: false
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Link"
                name: "link"
                widget: "string"
