backend:
  name: github
  repo: GSA/10x
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  branch: demo
  preview_context: federalist/build

media_folder: public/images
public_folder: public/images

collections:
  - name: settings
    extension: json
    publish: false
    label: Site Settings
    label_singular: Site Settings
    create: false
    delete: false
    show_preview_links: false
    identifier_field: settings
    editor:
      preview: false
    files:
      - label: Settings
        name: settings
        file: cms/settings.json
        fields:
          - label: Settings
            name: settings
            widget: hidden
            default: settings
          - label: Site Title
            name: title
            widget: string
          - label: Site Description
            name: description
            widget: string
          - name: customFields
            label: Custom Fields
            widget: list
            fields:
              - name: key
                label: Key
                widget: string
              - name: value
                label: Value
                widget: string
  - name: menu
    extension: json
    label: Menus
    label_singular: Menu
    folder: cms/menus
    create: true
    delete: true
    editor:
      preview: false
    slug: "{{key}}"
    fields:
      - name: key
        label: key
        widget: string
      - name: items
        label: Items
        widget: list
        fields:
          - label: Text
            name: text
            widget: string
          - label: Link
            name: link
            widget: string
          - label: Description
            name: desc
            width: string
          - label: img
            name: img
            widget: image
          - label: Items
            name: items
            widget: list
            fields:
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: string
  - name: page
    extension: json
    label: Pages
    label_singular: Page
    folder: cms/content/page
    create: true
    delete: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    identifier_field: title
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: Meta
        name: Meta
        required: false
        widget: "object"
        fields:
          - label: Description
            name: description
            widget: string
            required: false
          - label: Facebook Image
            name: fbImg
            widget: image
            required: false
          - label: Twitter Image
            name: twImg
            widget: image
            required: false
      - label: "Hero Content"
        name: "hero"
        widget: "markdown"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: project
    extension: json
    label: Projects
    label_singular: Project
    folder: cms/content/project
    create: true
    delete: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    identifier_field: title
    fields:
      - label: "Project Title"
        name: "title"
        widget: "string"
      - label: "Headline"
        name: "subtitle"
        widget: "string"
      - label: "Type"
        name: "projectType"
        widget: "select"
        options: ["Innovation", "Transformation", "Enhancement"]
      - label: "Project Link"
        name: "projectLink"
        widget: "string"
        required: false
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
      - label: "Phase"
        name: "phaseData"
        widget: "object"
        collapsed: true
        fields:
          - label: "Phase"
            name: "phase"
            widget: "select"
            options: ["1", "2", "3", "4"]
          - label: "Status"
            name: "status"
            widget: "select"
            options:
              [
                { label: "In Progress", value: "1" },
                { label: "Done", value: "2" },
                { label: "Graduated", value: "3" },
              ]
            default: "InProgress"
          - label: "Message"
            name: "message"
            hint: "Override the default Phase status message."
            widget: "string"
            required: false
      - label: "Topics"
        name: "topics"
        widget: "string"
        hint: "Separate tag values by comma."
        required: false
      - label: "Team"
        name: "team"
        widget: "object"
        required: false
        fields:
          - label: "Idea Submitter"
            name: "submitter"
            widget: "string"
            required: false
          - label: "Members"
            name: "members"
            widget: "text"
            required: false
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - label: "Text"
            name: "text"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
