backend:
  name: github
  repo: GSA/10x
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  # remember to change back when finished
  branch: feature/improve-cms-ux
  preview_context: federalist/build

media_folder: public/images
public_folder: public/images

#########################
types:
  #########################

  body: &body
    label: "Text Content"
    name: "body"
    widget: "markdown"

  button: &button
    label: Button
    name: button
    widget: "object"
    required: false
    fields:
      - label: "Text"
        name: "text"
        widget: string
        required: false
      - label: "Link"
        name: "link"
        widget: string
        required: false

  classname: &classname
    label: "Class override"
    hint: "Style your content with additional classes applied to the content container."
    name: className
    widget: string
    required: false

  headline: &headline
    label: "Headline"
    name: "subtitle"
    widget: "string"
    required: false

  level: &level
    label: Level
    name: level
    widget: select
    options: ["1", "2", "3", "4", "5"]

  link: &link
    label: "Link"
    name: "link"
    widget: string

  preFooter: &preFooter
    label: Pre-Footer
    name: footer
    hint: "Most pages use the '10x-in-the-wild' prefooter."
    default: "10x-in-the-wild"
    widget: relation
    collection: "footers"
    search_fields: ["slug"]
    value_field: "slug"
    display_fields: ["slug"]

  slug: &slug
    widget: string
    name: "slug"
    label: "Page Slug"
    required: true
    pattern:
      [
        "^[a-z0-9]+(?:-[a-z0-9]+)*$",
        "A slug can have no spaces or special characters",
      ]
    hint: "The page URL (do not include folder or file extension)"

  text: &text
    label: "Text"
    name: "text"
    widget: text

  title: &title
    label: Title
    name: title
    widget: string

#########################
modules:
  #########################

  modTitle: &modTitle
    label: Title
    name: title
    widget: "object"
    fields:
      - <<: *classname
      - <<: *title
      - <<: *level
        required: false
      - <<: *headline
        required: false

  modMarkdown: &modMarkdown
    label: "Markdown content"
    name: "markdown"
    widget: "object"
    fields:
      - <<: *classname
      - <<: *body
  
  modGhostwriter: &modGhostwriter
    label: "Ghostwriter hero"
    name: "ghostwriter"
    widget: "object"
    fields:
      - <<: *classname
      - <<: *body

  modCallout: &modCallout
    label: Callout
    name: callout
    widget: "object"
    fields:
      - <<: *classname
      - <<: *title
        required: false
      - <<: *headline
        label: "Subtitle"
        required: false
      - <<: *text
        required: false
      - <<: *button
      - label: variant
        name: variant
        widget: select
        options: ["none", "check", "number", "ringer"]
        hint: Default displays check
      - label: Items
        name: items
        widget: list
        summary: "Item"
        fields:
          - <<: *classname
          - <<: *body
            required: false

  modBreak: &modBreak
    label: Break
    name: break
    widget: "object"
    fields:
      - label: Color
        name: color
        widget: select
        required: false
        options:
          [
            "primary-lighter",
            "secondary",
            "accent-warm",
            "accent-cool",
            "base-lighter",
          ]
      - label: variant
        name: variant
        widget: select
        required: false
        options: [0, "wide"]

  modCards: &modCards
    label: Cards
    name: cards
    widget: "object"
    fields:
      - <<: *classname
      - <<: *title
        required: false
      - <<: *text
        required: false
      - label: "Columns"
        name: columns
        widget: select
        options: ["1", "2", "3", "4"]
        required: false
      - label: Items
        name: items
        widget: list
        summary: "Card"
        fields:
          - <<: *classname
          - <<: *body

  modLinks: &modLinks
    label: Links
    name: links
    widget: "object"
    fields:
      - <<: *classname
      - <<: *title
        required: false
      - <<: *headline
        required: false
      - <<: *text
        required: false
      - <<: *button
      - label: Items
        name: items
        widget: list
        fields:
          - <<: *text
          - <<: *link

  modList: &modList
    label: List
    name: list
    widget: "object"
    fields:
      - <<: *classname
      - <<: *title
        required: false
      - <<: *headline
        required: false
      - <<: *text
        required: false
      - <<: *button
      - label: Columns
        name: columns
        widget: select
        options: ["1", "2", "3"]
        required: false
      - label: Items
        name: items
        widget: list
        summary: "List Item"
        fields:
          - <<: *title
            required: false
          - <<: *text
            required: false

  modProjects: &modProjects
    label: Projects
    name: projects
    widget: "object"
    fields:
      - <<: *classname

  modPhase: &modPhase
    label: "Phase timeline graphic"
    name: phase
    widget: "boolean" #might be a boolean
    fields:
      - <<: *classname

  modSections: &modSections
    label: "Sections"
    name: "sections"
    widget: "list"
    hint: "Choose sections from the dropdown to fill out the page."
    types:
      - <<: *modBreak
      - <<: *modCallout
      - <<: *modCards
      - <<: *modLinks
      - <<: *modList
      - <<: *modMarkdown
      - <<: *modGhostwriter
      - <<: *modProjects
      - <<: *modTitle

  modSeo: &modSeo
    label: SEO
    name: seo
    widget: object
    fields:
      - <<: *title
        label: "Meta Title"
        required: true
        default: " | 10x.GSA.gov"
        hint: "Document title attribute - should include site title as well. e.g., 'Project Name Here - 10x Project | 10x.GSA.gov' "
      - <<: *text
        label: "Meta Description"
        hint: "Provide a keyword-rich description between 50–160 characters, which will show up in search results pages."
        name: description
        required: true
      # - name: custom
      #   label: Custom SEO fields
      #   widget: list
      #   hint: "Adds custom <meta> tag to the header, such as Open Graph tags."
      #   required: false
      #   fields:
      #     # come back to this -- some are property / content, some are name/value, etc
      #     - label: "Attribute"
      #       name: name
      #       widget: string
      #       required: false
      #     - label: "Value"
      #       name: content
      #       widget: string
      #       required: false

#########################
collections:
  #########################

  - name: settings
    extension: json
    publish: false
    label: Site Settings
    label_singular: Site Settings
    create: false
    delete: false
    show_preview_links: false
    identifier_field: settings
    editor:
      preview: false
    files:
      # see cms/__example-settings.json for example usage
      # - label: Settings
      #   name: settings
      #   file: cms/settings.json
      #   fields:
      #     - label: Settings
      #       name: settings
      #       widget: hidden
      #       default: settings
      #     - label: Site Title
      #       name: title
      #       widget: string
      #     - label: Site Description
      #       name: description
      #       widget: string
      #     - name: customFields
      #       label: Custom Fields
      #       widget: list
      #       fields:
      #         - name: key
      #           label: Key
      #           widget: string
      #         - name: value
      #           label: Value
      #           widget: string
      - label: 404 Content
        name: "404"
        file: cms/404.json
        fields:
          - <<: *modSections
            label: "404 Content"
            name: "404"
      - label: Redirects
        name: "redirects"
        file: cms/redirects.json
        fields:
          - label: Redirects
            name: redirects
            widget: list
            summary: "{{fields.origin}}"
            fields:
              - name: origin
                label: Origin URL
                widget: string
              - name: forward
                label: Forward URL
                widget: string

  - name: menu
    extension: json
    label: Nav menus
    label_singular: Nav menu
    folder: cms/menus
    create: true
    delete: true
    editor:
      preview: false
    slug: "{{key}}"
    fields:
      - name: key
        label: key
        widget: string
      - name: items
        label: Items
        widget: list
        summary: "Primary Item"
        types:
          - label: Page Link
            name: page
            widget: object
            fields:
              - label: Prefix
                name: prefix
                widget: string
                required: false
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: relation
                collection: "pages"
                search_fields: ["slug"]
                value_field: "slug"
                display_fields: ["title"]
          - label: Custom Link
            name: custom
            widget: object
            fields:
              - label: Prefix
                name: prefix
                widget: string
                required: false
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: list
          - label: Nested Link
            name: nested
            widget: object
            fields:
              - label: Prefix
                name: prefix
                widget: string
                required: false
              - label: Text
                name: text
                widget: string
              - label: Items
                name: items
                widget: list
                summary: "Subitem"
                types:
                  - label: Page Link
                    name: page
                    widget: object
                    fields:
                      - label: Prefix
                        name: prefix
                        widget: string
                        required: false
                      - label: Text
                        name: text
                        widget: string
                      - label: Link
                        name: link
                        widget: relation
                        collection: "pages"
                        search_fields: ["slug"]
                        value_field: "slug"
                        display_fields: ["title"]
                  - label: Custom Link
                    name: custom
                    widget: object
                    fields:
                      - label: Prefix
                        name: prefix
                        widget: string
                        required: false
                      - label: Text
                        name: text
                        widget: string
                      - label: Link
                        name: link
                        widget: list

  - name: pages
    label: Pages
    extension: json
    label_singular: Page
    folder: cms/content/page
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    identifier_field: slug
    summary: "{{title}} ({{slug}})"
    editor:
      preview: false
    fields:
      - <<: *title
        label: "Page title"
      - <<: *slug
      - <<: *modSeo
      - label: "Page Theme"
        name: "theme"
        required: false
        widget: "select"
        options: 
          - label: "1 - lilac-to-tiger wash"
            value: "1"
          - label: "2 - charcoal-to-lead with x's"
            value: "2"
          - label: "3 - smoke-to-ocean wash"
            value: "3"
          - label: "4 - smoke-to-tiger wash"
            value: "4"
          - label: "5 - charcoal-to-lead flat"
            value: "5"
          - label: "6 - smoke wash"
            value: "6"
          - label: "7 - ocean fade"
            value: "7"
          - label: "8 - lilac fade"
            value: "8"
      - label: "Page content sections"
        label_singular: "content"
        name: "sections"
        widget: "list"
        types:
          - <<: *modBreak
          - <<: *modCallout
          - <<: *modCards
          - <<: *modLinks
          - <<: *modList
          - <<: *modMarkdown
          - <<: *modGhostwriter
          - <<: *modProjects
          - <<: *modTitle
      - <<: *preFooter

  - name: projects
    extension: json
    label: Projects
    label_singular: Project
    folder: cms/content/project
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    identifier_field: slug
    summary: "{{title}} ({{slug}})"
    editor:
      preview: false
    fields:
      - <<: *slug
      - <<: *title
        label: "Project Page title"
      - <<: *headline
        label: "Project Page headline"
        hint: "Question posed at the top of the project page. Can be longer than Project Card headline below."
        required: false
      - <<: *modSeo
      - label: "Project Phase & Status"
        name: "phaseData"
        widget: "object"
        collapsed: true
        required: false
        hint: "Set the phase and status information here, to be used anywhere within the page content sections."
        fields:
          - label: "Phase"
            name: "phase"
            widget: "select"
            options: ["1", "2", "3", "4"]
            required: false
          - label: "Status"
            name: "status"
            widget: "select"
            required: false
            options:
              [
                { label: "In Progress", value: "1" },
                { label: "Done", value: "2" },
                { label: "Graduated", value: "3" },
              ]
            default: "InProgress"
          - label: "Message"
            name: "message"
            hint: "Override the default Phase status message."
            widget: "string"
            required: false
      - label: "Project Topics"
        name: "topics"
        widget: "string"
        hint: "Separate tag values by comma."
        required: false
      - label: "Project Type"
        name: "projectType"
        widget: "select"
        required: false
        options: ["Innovation", "Transformation", "Enhancement"]
      - label: "In a nutshell sidebar list"
        label_singular: "list item"
        name: "summary"
        hint: "These items fill out the 'In a nutshell' sidebar"
        widget: "list"
        required: false
        fields:
          - *text
      - label: "Team sidebar"
        name: "team"
        hint: "Provide the Idea Submitter and the rest of the project team in the sidebar."
        widget: "object"
        required: false
        fields:
          - label: "Idea Submitter"
            name: "submitter"
            widget: "string"
            required: false
            hint: "Name, Department or Agency"
          - label: "Members"
            name: "members"
            widget: "text"
            required: false
            hint: "Curly, Moe, and Larry."
      - label: "Links in sidebar list"
        label_singular: "link"
        name: "links"
        widget: "list"
        required: false
        fields:
          - <<: *text
            required: true
          - <<: *link
            required: true
      - <<: *body
        name: "intro"
        label: "Project Page Introduction"
        required: false
        hint: "Displays just below the Project Page Headline and Project Page Title."
      - label: "Project Page Sections"
        label_singular: "Project page section"
        name: "sections"
        widget: "list"
        required: false
        summary: "Project page section"
        hint: "Each section displays content items in a Card on the project detail page. Most project pages have 3 cards: 'Why this matters', 'What we did' or 'Our goal', and 'Next steps'."
        fields:
          - label: "Content items in this project section"
            label_singular: "Content item"
            name: "modules"
            widget: list
            required: false
            hint: "Choose sections from the dropdown to fill out the card."
            types:
              - <<: *modBreak
              - <<: *modCallout
              - <<: *modCards
              - <<: *modLinks
              - <<: *modList
              - <<: *modMarkdown
              - <<: *modPhase
              - <<: *modProjects
              - <<: *modTitle
      - <<: *preFooter
        required: false
      - label: "Project Card on /projects page"
        name: "card"
        hint: "Customize the Card content that will display on the Projects page"
        widget: "object"
        fields:
          - <<: *title
            label: "Project Card Title"
            required: false
            hint: "Project name to be used as card title (If not provided, defaults to Project Page Title above.)"
          - <<: *headline
            label: "Project Card Question"
            required: false
            hint: "Question posed at the top of the card. Uses Project Page Headline if not provided."
          - label: "Project Card External Url"
            name: "projectUrl"
            widget: "string"
            required: false
            hint: "If provided, this overrides the default link to the Project's Detail Page. Provide a full link including https:// for project cards that should link externally instead of the Project Detail Page."
          - label: "Project Card Excerpt"
            name: "excerpt"
            hint: "A short paragraph describing the project. If not provided, uses the project introduction."
            widget: "text"
            required: true
          - label: "Project Card Style"
            name: "template"
            hint: "Choose one of the card style templates for this project."
            widget: "select"
            required: true
            options:
              - label: "1 - Ocean splatter"
                value: "1"
              - label: "2 - Grimace wash"
                value: "2"
              - label: "3 - Tiger swipe"
                value: "3"
              - label: "4 - Ocean swirl"
                value: "4"
              - label: "5 - Tiger scratch"
                value: "5"
              - label: "6 - Grimace scribble"
                value: "6"
  - name: footers
    extension: json
    label: Footers
    label_singular: Footer
    folder: cms/content/footer
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    identifier_field: slug
    editor:
      preview: false
    fields:
      - <<: *slug
      - <<: *body
      - <<: *button
