name: SSR Build
on: "push"
jobs:
  ssr-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14

      - name: SSR Build
        run: |
          npm ci
          CI=false npm run federalist:build
